# Generated by Django 5.1 on 2024-08-23 21:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='record',
            name='certification',
        ),
        migrations.RemoveField(
            model_name='record',
            name='completion_date',
        ),
    ]
