# Generated by Django 5.1 on 2024-08-23 21:05

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0002_remove_record_certification_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='record',
            name='completion_date',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
