# Generated by Django 5.1 on 2024-08-23 21:25

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0003_record_completion_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='record',
            name='certification',
            field=models.FileField(default=django.utils.timezone.now, upload_to='files/'),
            preserve_default=False,
        ),
    ]
