# Generated by Django 5.1 on 2024-08-26 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0004_record_certification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='certification',
            field=models.FileField(upload_to=''),
        ),
    ]
